In [1]:
from nltk.cluster import KMeansClusterer
from nltk.cluster import euclidean_distance
from nltk.cluster.util import cosine_distance
from sklearn import metrics
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
import pandas as pd
import numpy as np
import matplotlib.pyplot as pl
import seaborn as sb

In [4]:
df = pd.read_csv("C:\\Users\\Rogonfu\\Downloads\\ucec_tcga_pan_can_atlas_2018\\ucec_tcga_pan_can_atlas_2018\\normals\\data_mrna_seq_v2_rsem_normal_samples.txt", sep="\t", header=None)

C:\Users\Rogonfu\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3146: DtypeWarning: Columns (1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

In [ ]:
x = np.array([[1,2,3,4,5,6], [6,5,4,3,2,1]])

In [ ]:
kmeans = KMeansClusterer(1, euclidean_distance, avoid_empty_clusters=True)
var = kmeans.cluster(x, True)

In [ ]:
t = np.array(kmeans.means())
print(x)

In [ ]:
print(t)

In [5]:
df

,0,1,2,3,4,5,6,7,8,9,...,26,27,28,29,30,31,32,33,34,35
0,Hugo_Symbol,Entrez_Gene_Id,TCGA-AJ-A3NC-11,TCGA-AJ-A3NE-11,TCGA-AJ-A3NH-11,TCGA-AX-A05Y-11,TCGA-AX-A0IZ-11,TCGA-AX-A0J0-11,TCGA-AX-A2HC-11,TCGA-AX-A2HD-11,...,TCGA-AJ-A2QL-11,TCGA-AX-A1CF-11,TCGA-AX-A1CI-11,TCGA-AX-A1CK-11,TCGA-AX-A2HA-11,TCGA-BK-A0CB-11,TCGA-BK-A13C-11,TCGA-DI-A2QU-11,TCGA-E6-A1M0-11,TCGA-FL-A1YM-11
1,NaN,100130426,0,0,0,0,0,0,0.5439,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,100133144,8.9708,9.9444,21.4457,9.4971,8.715,5.4959,1.3109,6.4454,...,26.99765367,24.96384786,10.03891719,20.68522387,35.90467895,10.64533342,9.379728063,3.325400145,7.433106762,23.05081756
3,UBE2Q2P2,100134869,8.8183,11.7437,26.2228,14.2228,4.7565,10.6965,5.7603,19.7404,...,24.31852398,74.39826061,18.22084028,16.2411899,15.96964343,9.314024979,1.541640855,10.2019395,12.99416235,18.715507
4,HMGB1P1,10357,146.379,144.945,156.711,113.787,139.565,177.959,143.153,75.0017,...,205.8923161,198.4449394,209.7707163,194.9221442,252.9379746,209.920282,284.4961396,247.5129763,128.5258923,201.6346335
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20527,ZYG11A,440590,0.4235,0,1.0251,0.4562,0,0,0.5439,0.9188,...,2.44542,-0.402069,0.990802,-0.402069,7.12777,1.9669,0.216561,0.613739,2.22401,-0.402069
20528,ZYG11B,79699,1246.93,847.442,729.89,1540.88,1546.11,1531.61,1428.38,874.698,...,950.353,1072.4,1436.36,1233.28,1357.4,2572,2040.26,2525.53,2259.9,2044.15
20529,ZYX,7791,12346.9,13672.3,3534.64,16686.5,10501.6,10037.8,24816.6,11557.6,...,3798.24,7018.02,5042.94,6232.33,10082.7,18340.5,15633.3,24701.3,7534.79,14709.7
20530,ZZEF1,23140,1334.18,1343.05,814.976,1168.66,998.964,1026.79,1051.97,993.224,...,1276.41,1548.09,1327.65,1357.54,1125.03,2195.67,1377.86,1223.89,1696.62,1158.8
20531,ZZZ3,26009,989.411,720.124,854.443,1011.75,883.938,969.638,594.523,655.105,...,662.811,739.975,854.907,748.809,640.079,931.898,924.37,835.717,1000.91,801.492